{% set version = "0.32" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fselector
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/FSelector_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/FSelector/FSelector_{{ version }}.tar.gz
  sha256: 3b2af0be0b651d93c5785f0d51f5075f0e3872a5f1c53ca05ef7d59b8b75baf9

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rweka
    - r-digest
    - r-entropy
    - r-randomforest
  run:
    - r-base
    - r-rweka
    - r-digest
    - r-entropy
    - r-randomforest

test:
  commands:
    - $R -e "library('FSelector')"           # [not win]
    - "\"%R%\" -e \"library('FSelector')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=FSelector
  license: GPL-2.0-only
  summary: Functions for selecting attributes from a given dataset. Attribute subset selection is the process of identifying and removing as much of the irrelevant and redundant information as possible.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: FSelector
# Type: Package
# Title: Selecting Attributes
# Version: 0.31
# Date: 2018-05-16
# Author: Piotr Romanski, Lars Kotthoff
# Maintainer: Lars Kotthoff <larsko@uwyo.edu>
# Description: Functions for selecting attributes from a given dataset. Attribute subset selection is the process of identifying and removing as much of the irrelevant and redundant information as possible.
# License: GPL-2
# Imports: randomForest, RWeka, digest, entropy
# Suggests: mlbench, rpart
# LazyLoad: yes
# NeedsCompilation: no
# Packaged: 2018-05-16 20:59:58 UTC; larsko
# Repository: CRAN
# Date/Publication: 2018-05-16 21:38:09 UTC
