travis:
  secure:
    BINSTAR_TOKEN: ipt/DIkSfILzhSxFyYuMYzXD4NkZUg0fXMDiok2jK3bSEEVpLQnrGeHzRwgox4Ox7BGNBow28UgPnHto6pSFISAEbJ6j9Onjf/aYiA10S0G0tqNNAay8Wp+xeuv7yLUHH2WbzUSysb1I3353+I4CMFaoUJAItFG5j3+83TAh7UsFLyPNigtn8gu/pqHoz0pK94mYCy6OlnJ8vl+TnZHU0Qne8+qvSgAmvhOXgLRB1PUqUum4pOO4bT6NACDT8wp1kHr8Dy8pp1OHRwq6y/sh+2ijKFAsaX517SwVAUnWgZ0fUJc8CjPlE8xCNBYqzFMXtGZNfnQqaoB6RA2p/Ee59ejeihrMVp1wj8877dhRwt0MfVar55gyQw5mPPR3tlzh/lvw8+l53GCVdTwfplQYvcnKK+8tNwCl8FXDrqYyp8tObQK3aJqmVJrUBdie0e3tq1V55iXjzYKNp66SA0n60YFYJk3WzBZAQNTsKeOFjBuGn2/0cBPmoZ7P+rEQSbmH3zdA0mGdQM1M4F31Z+vD6hYsijA8P5JjaN5p85bbd2S8YeONhOUlSPRXfXeUaxW0G6AWWcMXr+S8ZkOHmKxr+vIkcjnAfAIYWwHZsxxJqj9arM3v3WDMCAyW/J3t2BIBmj8KbOyjYOvboWL+OniSUJzGfFcO2uHp2qjheecza0s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
